name: Deploy to Dev

on:
  push:
    branches:
      - 'main'

env:
  php_version: '8.1'
  pantheon_env: 'dev'
  pantheon_repo: ${{ secrets.PANTHEON_REPO }}

jobs:
  deploy:
    name: Deploy to Pantheon Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Place SSH key
        uses: shimataro/ssh-key-action@v2 # v2.1.0
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Prepare code for deployment
        run: |
          git config --global user.email "trongkhanh2014@gmail.com"
          git config --global user.name "khanh.dt"
          commit_message=$(git log -1 --pretty=%B)
          rm -rf .git
          git init
          git config pull.rebase false
          git add .
          git commit -m "Automated deploy: $commit_message" >/dev/null
          
      - name: Push code to Pantheon Dev
        run: |
          git remote add patheon ${{ secrets.PANTHEON_REPO }}
          git push patheon master
      # There is no easy way to know when the code has actually synced to the Pantheon environment so we can't reliably
      # run Drush commands immediately after pushing code. Thus, we run database updates, import config, and disable
      # maintenance mode using Pantheon's Quicksilver scripting (see web/private/quicksilver/sync_code.php referenced by
      # pantheon.yml).
